name: NeoSpeedZero
version: '${version}'
api-version: '26.3'
authors:
  - teddyxlandlee
main: xland.mcmod.neospeedzero.paper.NeoSpeedZeroPaper
bootstrapper: xland.mcmod.neospeedzero.paper.NeoSpeedZeroPaperBootstrap
